UD-9  [WIP] [fix]: upgrade package.json

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,6 @@
-echo "Init lint"
+# echo "Init lint"
 
-npx @biomejs/biome format --write ./src || (echo "Biome can't resolve errors" && exit 1)
+# pnpm @biomejs/biome format --write ./src || (echo "Biome can't resolve errors" && exit 1)
 
-echo "Lint success"
+# echo "Lint success"
+# #
