pre-commit and commit-msg

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,5 @@
-echo "Init lint"
+#echo "Init lint"
 
-bunx @biomejs/biome format --write ./src || (echo "Biome can't resolve errors" && exit 1)
+#bunx @biomejs/biome format --write ./src || (echo "Biome can't resolve errors" && exit 1)
 
-echo "Lint success"
+#echo "Lint success"
